name: Dev tools workflow
on:
  pull_request:
    types:
      - unlabeled
      - labeled
      - synchronize
      - opened
      - reopened
    paths-ignore:
      - '.gitignore'
      - '.metadata'
      - '.github/**'
      - 'README.md'
      - 'README.fr.md'
      - 'android/fastlane/**'
      - 'ios/fastlane/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:     
  bump-version:
    name: Bump app version using PR labels
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        uses: apomalyn/bump-version-using-labels@v1.2.1
        with:
          file_path: 'pubspec.yaml'
          reference_branch: 'master'
